service: honeylib-api
runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_NAME: honeylib-api
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:cHCVRmMM51Wywa4wN0Zju09XVw5xosXL1hF8IV0y/oE=
  STORAGE_DIR: /tmp
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: student_db
  DB_USERNAME: root
  DB_PASSWORD: r00t
  DB_SOCKET: "/cloudsql/honeylib-197014:asia-northeast1:honeylib-fit"
beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: "honeylib-197014:asia-northeast1:honeylib-fit"